$PBExportHeader$u_tabpg_dwproperty_srvrowmanager.sru
$PBExportComments$Extension DataWindow Property - The RowManager service tabpage
forward
global type u_tabpg_dwproperty_srvrowmanager from pro_u_tabpg_dwproperty_srvrowmanager
end type
end forward

global type u_tabpg_dwproperty_srvrowmanager from pro_u_tabpg_dwproperty_srvrowmanager
end type
global u_tabpg_dwproperty_srvrowmanager u_tabpg_dwproperty_srvrowmanager

on u_tabpg_dwproperty_srvrowmanager.create
call pro_u_tabpg_dwproperty_srvrowmanager::create
end on

on u_tabpg_dwproperty_srvrowmanager.destroy
call pro_u_tabpg_dwproperty_srvrowmanager::destroy
end on

