$PBExportHeader$u_tabpg_dwproperty_srvrowselection.sru
$PBExportComments$Extension DataWindow Property - The RowSelection service tabpage
forward
global type u_tabpg_dwproperty_srvrowselection from pro_u_tabpg_dwproperty_srvrowselection
end type
end forward

global type u_tabpg_dwproperty_srvrowselection from pro_u_tabpg_dwproperty_srvrowselection
end type
global u_tabpg_dwproperty_srvrowselection u_tabpg_dwproperty_srvrowselection

on u_tabpg_dwproperty_srvrowselection.create
call pro_u_tabpg_dwproperty_srvrowselection::create
end on

on u_tabpg_dwproperty_srvrowselection.destroy
call pro_u_tabpg_dwproperty_srvrowselection::destroy
end on

