$PBExportHeader$u_tabpg_dwproperty_srvdropdownsearch.sru
$PBExportComments$Extension DataWindow Property - The DropDownSearch service tabpage
forward
global type u_tabpg_dwproperty_srvdropdownsearch from pro_u_tabpg_dwproperty_srvdropdownsearch
end type
end forward

global type u_tabpg_dwproperty_srvdropdownsearch from pro_u_tabpg_dwproperty_srvdropdownsearch
end type
global u_tabpg_dwproperty_srvdropdownsearch u_tabpg_dwproperty_srvdropdownsearch

on u_tabpg_dwproperty_srvdropdownsearch.create
call pro_u_tabpg_dwproperty_srvdropdownsearch::create
end on

on u_tabpg_dwproperty_srvdropdownsearch.destroy
call pro_u_tabpg_dwproperty_srvdropdownsearch::destroy
end on

