$PBExportHeader$u_tabpg_dwproperty_srvcalculator.sru
$PBExportComments$Extension DataWindow Property - The Calculator service tabpage
forward
global type u_tabpg_dwproperty_srvcalculator from pro_u_tabpg_dwproperty_srvcalculator
end type
end forward

global type u_tabpg_dwproperty_srvcalculator from pro_u_tabpg_dwproperty_srvcalculator
end type
global u_tabpg_dwproperty_srvcalculator u_tabpg_dwproperty_srvcalculator

on u_tabpg_dwproperty_srvcalculator.create
call pro_u_tabpg_dwproperty_srvcalculator::create
end on

on u_tabpg_dwproperty_srvcalculator.destroy
call pro_u_tabpg_dwproperty_srvcalculator::destroy
end on

